In [2]:
# Data Preprocessing
import sklearn

In [16]:
data = [
    {'age':4, 'height':96.0},
    {'age':1, 'height':None},
    {'age': None, 'height':88.0},
    {'age':2, 'height':81.0}
]

In [17]:
# Feature Extration - DictVectorize
from sklearn.feature_extraction import DictVectorizer


dv = DictVectorizer(sparse = False)
data_vec = df.fit_transform(data)

In [18]:
# Cleaning Data
from sklearn.impute import SimpleImputer

si = SimpleImputer(strategy='mean')
si.fit_transform(data_vec)

array([[ 4.        , 96.        ],
       [ 1.        , 88.33333333],
       [ 2.33333333, 88.        ],
       [ 2.        , 81.        ]])

In [22]:
#Transformation
from sklearn.discriminant_analysis import StandardScaler

x = [[4,], [3,] ,[2,] ,[5,] ,[6]]
ss = StandardScaler()
ss.fit_transform(x)

array([[ 0.        ],
       [-0.70710678],
       [-1.41421356],
       [ 0.70710678],
       [ 1.41421356]])

In [23]:
from sklearn.preprocessing import MinMaxScaler

x = [[15], [2], [5], [-2], [-5]]
mms = MinMaxScaler()
mms.fit_transform(x)

array([[1.  ],
       [0.35],
       [0.5 ],
       [0.15],
       [0.  ]])

In [25]:
from sklearn.preprocessing import MaxAbsScaler


x = [[4],[2],[5],[-1],[-100]]

mas = MaxAbsScaler()
mas.fit_transform(x)

array([[ 0.04],
       [ 0.02],
       [ 0.05],
       [-0.01],
       [-1.  ]])

In [26]:
# AQ2 Q4

In [27]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

X = np.array([[1], [2], [3]])
ft = FunctionTransformer(np.mean)
ft.fit_transform(X)

np.float64(2.0)

In [2]:
# Categorical Transformers
# One Hot Encoder
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()


In [11]:
data = [[1], [2], [3], [1]]
ohe_result = ohe.fit_transform(data)
print(ohe_result.shape)
print(ohe_result)

(4, 3)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 0)	1.0


In [12]:
from sklearn.calibration import LabelEncoder

le = LabelEncoder()

In [13]:
data = [[1],[2],[6],[1],[8],[6]]
le.fit_transform(data)

/Users/satviksawhney/Downloads/IITMadras/MLP (Practical)/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, 0, 3, 2])

In [14]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

data = [[1, 'Male'], [2, 'Female'], [6, 'Female'], [1, 'Male'], [8, 'Male'], [6, 'Female']]

In [15]:
oe.fit_transform(data)

array([[0., 1.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [3., 1.],
       [2., 0.]])

In [19]:
from sklearn.preprocessing import MultiLabelBinarizer, LabelBinarizer

lb = LabelBinarizer()
mlb = MultiLabelBinarizer()