# Feaure Extraction
- Dictionary Vectorizer - Converts lists of mappings of feature name and feature value into a matrix


In [1]:
data = [
    {
        'age':4, "height":96.0
    },
    {
        'age':6, "height":108.0
    },
    {
        'age':9, "height":173.0
    },
    {
        'age':10, "height":54.0
    },
]

In [5]:
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
vectorized_data = dv.fit_transform(data)

In [11]:
print(vectorized_data)
print(type(vectorized_data))
print(data)
print(type(data))

[[  4.  96.]
 [  6. 108.]
 [  9. 173.]
 [ 10.  54.]]
<class 'numpy.ndarray'>
[{'age': 4, 'height': 96.0}, {'age': 6, 'height': 108.0}, {'age': 9, 'height': 173.0}, {'age': 10, 'height': 54.0}]
<class 'list'>


In [12]:
data_back = dv.inverse_transform(vectorized_data)
print(data_back)
print(type(data_back))

[{'age': np.float64(4.0), 'height': np.float64(96.0)}, {'age': np.float64(6.0), 'height': np.float64(108.0)}, {'age': np.float64(9.0), 'height': np.float64(173.0)}, {'age': np.float64(10.0), 'height': np.float64(54.0)}]
<class 'list'>


# Cleaning Data
- Simple Imputer - Fills missing values with one of the following stratergies
- - mean
- - median
- - most_frequesnt
- - constant

In [14]:
import numpy as np

In [16]:
matrix = np.array([[7, 1],[np.nan, 8], [2, np.nan], [9,6]])
print(matrix)

[[ 7.  1.]
 [nan  8.]
 [ 2. nan]
 [ 9.  6.]]


In [18]:
from sklearn.impute import SimpleImputer
si_mean = SimpleImputer(strategy="mean")
si_median = SimpleImputer(strategy="median")
si_most_frequent = SimpleImputer(strategy="most_frequent")
si_constant = SimpleImputer(strategy="constant")

In [19]:
matrix_mean = si_mean.fit_transform(matrix)
print(matrix_mean)

[[7. 1.]
 [6. 8.]
 [2. 5.]
 [9. 6.]]


In [20]:
matrix_median = si_median.fit_transform(matrix)
print(matrix_median)

[[7. 1.]
 [7. 8.]
 [2. 6.]
 [9. 6.]]


In [23]:
matrix_most_frequent = si_most_frequent.fit_transform(matrix)
print(matrix_most_frequent)

[[7. 1.]
 [2. 8.]
 [2. 1.]
 [9. 6.]]


In [24]:
from sklearn.impute import KNNImputer


In [26]:
matrix_KNN = np.array([[1, 2, np.nan], [3, 4, 3], [np.nan, 6, 5], [8, 8, 7]])
print(matrix_KNN)

[[ 1.  2. nan]
 [ 3.  4.  3.]
 [nan  6.  5.]
 [ 8.  8.  7.]]


In [27]:
knni = KNNImputer()

matrix_knn_transformed = knni.fit_transform(matrix_KNN)

print(matrix_knn_transformed) 

[[1. 2. 5.]
 [3. 4. 3.]
 [4. 6. 5.]
 [8. 8. 7.]]


In [28]:
knni2 = KNNImputer(n_neighbors=2, weights="uniform")

matrix_knn_transformed2 = knni2.fit_transform(matrix_KNN)

print(matrix_knn_transformed2) 

[[1.  2.  4. ]
 [3.  4.  3. ]
 [5.5 6.  5. ]
 [8.  8.  7. ]]


# Feature Scaling

## Numeric Transformer

In [29]:
from sklearn.preprocessing import StandardScaler

In [44]:
X_S = np.array([[4,], [3,], [2,], [5,], [6,]])
print(X_S)

[[4]
 [3]
 [2]
 [5]
 [6]]


In [45]:
ss = StandardScaler()
new_X_SS = ss.fit_transform(X_S)
print(new_X_SS)

[[ 0.        ]
 [-0.70710678]
 [-1.41421356]
 [ 0.70710678]
 [ 1.41421356]]


In [47]:
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler()

X_mss = mms.fit_transform(X_S)

print(X_mss)

[[0.5 ]
 [0.25]
 [0.  ]
 [0.75]
 [1.  ]]


In [48]:
from sklearn.preprocessing import MaxAbsScaler

mas = MaxAbsScaler()

X_mas = mas.fit_transform(X_S)

print(X_mas)

[[0.66666667]
 [0.5       ]
 [0.33333333]
 [0.83333333]
 [1.        ]]


In [49]:
# Function Transformer - Custom Transformer

X_FT = np.array([[128, 2], [2, 256], [4, 1], [512, 64]])
print(X_FT)

[[128   2]
 [  2 256]
 [  4   1]
 [512  64]]


In [50]:
from sklearn.preprocessing import FunctionTransformer

ft = FunctionTransformer(np.log2)

new_x_ft = ft.fit_transform(X_FT)

print(new_x_ft)

[[7. 1.]
 [1. 8.]
 [2. 0.]
 [9. 6.]]


In [51]:
# Polynomial Transformation

X_PF= np.array([[1, 1], [2, 2], [3, 3], [4, 4]])

from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree=2)

new_pf = pf.fit_transform(X_PF)

print(new_pf)

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  2.  2.  4.  4.  4.]
 [ 1.  3.  3.  9.  9.  9.]
 [ 1.  4.  4. 16. 16. 16.]]


## Categorical Transformers

In [59]:
# One Hot Encoder

X_CT = np.array([[1], [2], [6], [1], [8], [6]])
print(X_CT)

[[1]
 [2]
 [6]
 [1]
 [8]
 [6]]


In [62]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit_transform(X_CT)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 4)>

In [64]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

le_x = le.fit_transform(X_CT)

/Users/satviksawhney/Downloads/IITMadras/MLP (Practical)/.venv/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 2, 0, 3, 2])