# Feature Selcetion

## Filter Based
- Variance Threshold
- SlectKBest
- SelectPercentile
- GenericUnivariateSelect

## Wrapper Based
- RecursiveFeatureElimination
- RecursiveFeatureEliminationCrossValidation
- SelectFromModel
- SequentialFeatureSelection

In [2]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13], [14, 15, 16]])
y = np.array([[6], [15], [24], [36], [45]])

print(x)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]]
[[ 6]
 [15]
 [24]
 [36]
 [45]]


In [4]:
# SelectKBest

from sklearn.feature_selection import SelectKBest, chi2

skb = SelectKBest(chi2, k=2)

x_np = skb.fit_transform(x, y)
# Select 20 best features based on chi-squaring function

print(x_np)

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [11 12]
 [14 15]]


In [5]:
from sklearn.feature_selection import SelectPercentile

sp = SelectPercentile(chi2, percentile=20)

# select top 20 percentiles best feature

x_sp = sp.fit_transform(x, y)

print(x_sp)

[[ 1]
 [ 4]
 [ 7]
 [11]
 [14]]


In [8]:
# Gneric Univariate Select

from sklearn.feature_selection import GenericUnivariateSelect

generic = GenericUnivariateSelect(chi2, mode = 'k_best', param = 2)

X_new = generic.fit_transform(x, y)

print(X_new)

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [11 12]
 [14 15]]


## Wrapper Based

In [10]:
# RFE
from sklearn.feature_selection import RFE

rfe = RFE(estimator="mean")



In [12]:
# SelectFromModel
# from sklearn.linear_model import LinarCV
# from sklearn.feature_selection import SelectFromModel

# clf = LinarCV(c=0.01, penalty ="l1", dual="false")
# clf = clf.fit(X, y)
# clf.coef_

# model = SelectFromModel(clf, prefit=True)
# X_new = model.tramsform(X)

In [11]:
# Sequential Feature Selection
## Forward Selection - Starting with 0 features and add one feature with every iteration
## Backward Selection - Start with all features and discard one feature each iteration