In [1]:
import numpy as np

## Comparing performance with lists, etc.

In [2]:
N = 100000000

In [3]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

CPU times: user 8.76 s, sys: 1.21 s, total: 9.96 s
Wall time: 10.7 s


In [4]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

CPU times: user 3.09 s, sys: 2.3 s, total: 5.39 s
Wall time: 6.34 s


In [5]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

CPU times: user 1.1 s, sys: 898 ms, total: 2 s
Wall time: 2.04 s


In [6]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

CPU times: user 5.99 s, sys: 1.57 s, total: 7.56 s
Wall time: 7.88 s


In [7]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

CPU times: user 1.42 s, sys: 1.28 s, total: 2.7 s
Wall time: 2.83 s


In [8]:
%%time
arr = np.arange(N)
arr = arr * arr

CPU times: user 96.1 ms, sys: 227 ms, total: 323 ms
Wall time: 483 ms


In [9]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

CPU times: user 47.1 ms, sys: 64.7 ms, total: 112 ms
Wall time: 140 ms


# Creating np Arrays

In [10]:
arr = np.arange(5)

In [11]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [12]:
arr = np.array([0.0, 2, 4, 6, 8])

In [13]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [14]:
arr

array([0., 2., 4., 6., 8.])

In [15]:
arr.dtype

dtype('float64')

In [16]:
arr.ndim

1

In [17]:
arr.shape

(5,)

In [18]:
arr.size

5

In [19]:
arr.itemsize

8

In [20]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [21]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr2d.ndim

2

In [23]:
arr2d.shape

(2, 3)

In [24]:
arr2d.size

6

In [25]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [26]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
arr3d.shape

(2, 2, 3)

In [28]:
arr3d.ndim

3

In [29]:
arr3d.size

12

In [30]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [31]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [32]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
np.random.randn(2, 3)

array([[-1.5455287 ,  0.89589092,  1.02664459],
       [ 1.18317428,  0.23694716, -0.48150712]])

In [34]:
np.random.rand(2, 3)

array([[0.96577242, 0.27283511, 0.82556603],
       [0.40557455, 0.63210138, 0.00840536]])

In [35]:
np.random.rand(10, 1)

array([[0.87075557],
       [0.53396595],
       [0.31699427],
       [0.31728574],
       [0.00909167],
       [0.45216122],
       [0.65235514],
       [0.72201111],
       [0.83308972],
       [0.9258027 ]])

In [36]:
np.random.randint(0, 100, (2, 3))

array([[16, 49, 83],
       [66, 96, 41]])

In [37]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [38]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [39]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [40]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [41]:
arr = np.array(str_arr, dtype='float')

In [42]:
arr

array([1.4, 2.1, 1.1])

## indexing

In [43]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [44]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [45]:
arr3d[0, 0, 0]

np.int64(1)

In [46]:
arr3d[1, 0, 2]

np.int64(9)

In [47]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

np.int64(9)

In [48]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [49]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [50]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [51]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [52]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [53]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [54]:
arr_slice = arr3d[:, :, 0:2]

In [55]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [56]:
arr_slice.ndim

3

In [57]:
arr_slice.shape

(2, 2, 2)

In [58]:
arr_slice[0, 0, 1]

np.int64(2)

In [59]:
arr_slice[0, 0, 0] = 1729

In [60]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [61]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [62]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [63]:
arr_slice[0, 0, 0] = 1

In [64]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [65]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [66]:
arr = np.random.randint(0, 10, (5))

In [67]:
arr

array([9, 9, 3, 0, 6])

In [68]:
my_indices = [1, 3, 4]

In [69]:
arr[my_indices]

array([9, 0, 6])

# Numpy Operations

In [70]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [71]:
arr1

array([[0.636566  , 0.03714845, 0.83312832, 0.53926129],
       [0.17600272, 0.85789205, 0.68123637, 0.81211444],
       [0.73327597, 0.7614716 , 0.74265071, 0.9495042 ]])

In [72]:
arr2

array([[0.29696181, 0.5451808 , 0.0918322 , 0.87855641],
       [0.53672934, 0.54993596, 0.71340771, 0.52954013],
       [0.44274885, 0.92270454, 0.24520478, 0.71784257]])

In [73]:
arr1 + arr2

array([[0.93352781, 0.58232925, 0.92496052, 1.41781769],
       [0.71273206, 1.407828  , 1.39464408, 1.34165457],
       [1.17602482, 1.68417614, 0.98785549, 1.66734677]])

In [74]:
arr1 - arr2

array([[ 0.33960418, -0.50803234,  0.74129612, -0.33929512],
       [-0.36072662,  0.30795609, -0.03217134,  0.28257431],
       [ 0.29052712, -0.16123295,  0.49744593,  0.23166163]])

In [75]:
arr1 * arr2

array([[0.18903579, 0.02025262, 0.07650801, 0.47377146],
       [0.09446582, 0.47178568, 0.48599928, 0.43004719],
       [0.32465709, 0.7026133 , 0.18210151, 0.68159453]])

In [76]:
arr1 / arr2

array([[2.14359547, 0.06813969, 9.07228976, 0.61380383],
       [0.32791708, 1.55998537, 0.95490469, 1.53362209],
       [1.65618944, 0.82526048, 3.02869585, 1.32271927]])

In [77]:
np.exp(arr1)

array([[1.88997953, 1.03784708, 2.3005042 , 1.71473969],
       [1.1924413 , 2.35818451, 1.97631968, 2.25266608],
       [2.08188966, 2.14142522, 2.1014986 , 2.58442798]])

In [78]:
np.log(np.exp(arr1))

array([[0.636566  , 0.03714845, 0.83312832, 0.53926129],
       [0.17600272, 0.85789205, 0.68123637, 0.81211444],
       [0.73327597, 0.7614716 , 0.74265071, 0.9495042 ]])

In [79]:
np.sin(arr1)

array([[0.59443753, 0.03713991, 0.74003898, 0.51350225],
       [0.17509545, 0.75646557, 0.62975391, 0.72574346],
       [0.66930722, 0.68998737, 0.67624301, 0.81312701]])

In [80]:
np.cos(arr1)

array([[0.8041418 , 0.99931008, 0.67256398, 0.85808825],
       [0.98455146, 0.65403351, 0.7767947 , 0.68796543],
       [0.74298576, 0.72382141, 0.73667862, 0.58208631]])

In [81]:
np.sqrt(arr1)

array([[0.79785086, 0.19273934, 0.91275863, 0.73434412],
       [0.41952678, 0.92622462, 0.82537044, 0.90117392],
       [0.85631535, 0.8726234 , 0.86177184, 0.97442506]])

In [82]:
arr_inv = 1 / arr1

In [83]:
arr_inv

array([[ 1.57092902, 26.91902168,  1.2002953 ,  1.85438864],
       [ 5.6817304 ,  1.16564783,  1.46791928,  1.23135355],
       [ 1.36374304,  1.31324662,  1.34652803,  1.05318123]])

In [84]:
arr1 = np.zeros((3, 5))

In [85]:
arr_inv = 1/arr1

/var/folders/z4/nk6c6p514xb426nd9nr8d29w0000gn/T/ipykernel_32691/2508733167.py:1: RuntimeWarning: divide by zero encountered in divide
  arr_inv = 1/arr1


In [86]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [87]:
np.isinf(arr_inv[0,0])

np.True_

In [88]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [89]:
arr1 = np.arange(6)

In [90]:
arr1.shape

(6,)

In [91]:
arr1

array([0, 1, 2, 3, 4, 5])

In [92]:
arr1 = arr1.reshape((3, 2))

In [93]:
arr1.shape

(3, 2)

In [94]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
arr2 = np.arange(6).reshape((3, 2))

In [96]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [97]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [98]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [99]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [100]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [101]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [103]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [104]:
arr2 = np.ones((1, 4))

In [105]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [110]:
arr1 = np.arange(5)

In [111]:
arr2 = np.arange(5)

In [112]:
print(arr1.shape, arr2.shape)

(5,) (5,)


In [113]:
arr1 + arr2

array([0, 2, 4, 6, 8])

In [116]:
# arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

In [117]:
arr = np.random.rand(3, 3)

In [118]:
arr

array([[0.14674411, 0.44035336, 0.59177314],
       [0.38517458, 0.46931412, 0.42119431],
       [0.93526434, 0.88489289, 0.45297475]])

In [119]:
arr.T

array([[0.14674411, 0.38517458, 0.93526434],
       [0.44035336, 0.46931412, 0.88489289],
       [0.59177314, 0.42119431, 0.45297475]])

# File handling

In [122]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: could not convert string 'Earth' to float64 at row 0, column 1.

In [130]:
planets_small = np.loadtxt("planets_small.txt")

In [131]:
# planets_small = np.loadtxt("planets_small.txt", 
#                            skiprows = 1,
#                            usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [135]:
planets_small

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [133]:
planets_small.shape

(3, 3)

In [134]:
planets = np.loadtxt("planets.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

FileNotFoundError: planets.txt not found.

In [0]:
planets = np.genfromtxt("planets.txt", 
                        skip_header=1, 
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
planets.shape

(20, 9)

In [0]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [0]:
planets_new = np.nan_to_num(planets, nan=-1)

In [0]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [0]:
np.savetxt('planets_new.txt', planets_new, 
           delimiter=',')

In [0]:
np.save("planets_new", planets_new)

In [0]:
!ls -lh

total 24K
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [0]:
np.savez("many_arrs", arr1, arr2, arr3)

In [0]:
!ls -lh

total 1.8M
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arrs = np.load('many_arrs.npz')

In [0]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [0]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [0]:
arrs['arr_0'].shape

(1000, 10)

In [0]:
np.savez_compressed('many_arrs_compressed', 
                    arr1, arr2, arr3)

In [0]:
!ls -lh

total 3.3M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data


In [0]:
arr1 = np.zeros((10000, 10000))

In [0]:
np.savez("zeros", arr1)

In [0]:
np.savez_compressed("zeros_compressed", arr1)

In [0]:
!ls -lh

total 767M
-rw-r--r-- 1 root root 1.6M Mar 16 14:54 many_arrs_compressed.npz
-rw-r--r-- 1 root root 1.7M Mar 16 14:52 many_arrs.npz
-rw-r--r-- 1 root root 1.6K Mar 16 14:47 planets_new.npy
-rw-r--r-- 1 root root 4.5K Mar 16 14:46 planets_new.txt
-rw-r--r-- 1 root root  254 Mar 16 14:38 planets_small.txt
-rw-r--r-- 1 root root 1.5K Mar 16 14:42 planets.txt
drwxr-xr-x 1 root root 4.0K Mar  3 18:11 sample_data
-rw-r--r-- 1 root root 760K Mar 16 14:56 zeros_compressed.npz
-rw-r--r-- 1 root root 763M Mar 16 14:55 zeros.npz


# Stats with NumPy

In [0]:
arr = np.random.rand(10000000,)

In [0]:
np.amin(arr)

2.9102073150211183e-06

In [0]:
np.amax(arr)

0.9999915329470833

In [0]:
np.mean(arr)

0.49835265487727426

In [0]:
np.var(arr)

0.08305664817400735

In [0]:
np.std(arr)

0.28819550338963884

In [0]:
np.median(arr)

0.49774252046580314

In [0]:
np.percentile(arr, 50)

0.49774252046580314

In [0]:
np.percentile(arr, 10)

0.10024188502450737

In [0]:
np.percentile(arr, 90)

0.8985023145814922

In [0]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

CPU times: user 280 ms, sys: 36 ms, total: 316 ms
Wall time: 319 ms


In [0]:
print(iqr)

0.49950783658626163


In [0]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

CPU times: user 210 ms, sys: 0 ns, total: 210 ms
Wall time: 210 ms


In [0]:
print(quartiles)

[0.24824011 0.74774795]


In [0]:
print(iqr)

0.49950783658626163


In [0]:
(arr - np.mean(arr))/np.std(arr)

array([-1.2076022 , -1.01987303,  1.51760917, ..., -0.47830944,
       -0.33409969,  1.14824894])

In [0]:
np.histogram(arr)

(array([ 999463,  998650, 1000122,  998223, 1000173, 1000919,  998865,
        1000985, 1001600, 1001000]),
 array([8.45622383e-09, 9.99999856e-02, 1.99999963e-01, 2.99999940e-01,
        3.99999917e-01, 4.99999894e-01, 5.99999871e-01, 6.99999849e-01,
        7.99999826e-01, 8.99999803e-01, 9.99999780e-01]))

In [0]:
np.histogram(arr, bins=5)

(array([1998113, 1998345, 2001092, 1999850, 2002600]),
 array([8.45622383e-09, 1.99999963e-01, 3.99999917e-01, 5.99999871e-01,
        7.99999826e-01, 9.99999780e-01]))

In [0]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2497818, 2498813, 2500099, 2503270]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [0]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [0]:
np.digitize(arr, bins)

array([1, 1, 4, ..., 2, 2, 4])

In [0]:
arr1 = np.random.randint(0, 10, (10))

In [0]:
arr1

array([2, 8, 8, 2, 6, 0, 8, 2, 7, 9])

In [0]:
bins = [0, 6, 10]

In [0]:
np.digitize(arr1, bins)

array([1, 2, 2, 1, 2, 1, 2, 1, 2, 2])

In [0]:
np.digitize(arr1, bins, right=True)

array([1, 2, 2, 1, 1, 0, 2, 1, 2, 2])

In [0]:
arr1 = np.random.randint(50, 80, 100) # weight

In [0]:
arr2 = np.random.randint(150, 185, 100) # heights

In [0]:
arr3 = np.random.randint(17, 22, 100) # age

In [0]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [0]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [0]:
arr2d = np.vstack((arr1, arr2, arr3))

In [0]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [0]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [0]:
np.mean(arr2d, axis=1)

array([ 64.48, 167.23,  18.96])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [0]:
arr = np.random.rand(1000)

In [0]:
mean = np.mean(arr)

In [0]:
arr1 = arr - mean

In [0]:
np.mean(arr1)

-7.105427357601002e-18

## Computing mean with smaller set of values

In [0]:
arr = np.random.rand(1000)

In [0]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

In [0]:
np.cumsum?

In [0]:
means = np.cumsum(arr)/np.arange(1,1001)

In [0]:
means[0:15]

array([0.80334668, 0.47415025, 0.50657624, 0.57224576, 0.6124674 ,
       0.51811314, 0.5048491 , 0.51491554, 0.49235724, 0.54249526,
       0.52085287, 0.48670218, 0.48395448, 0.45357307, 0.48506273])

## Effect of outliers on mean and median

In [0]:
arr = np.random.randint(1, 100, 100)

In [0]:
np.mean(arr)

50.09

In [0]:
np.median(arr)

50.0

In [0]:
arr = np.append(arr, [1000, 2000])

In [0]:
arr.shape

(102,)

In [0]:
np.mean(arr)

78.51960784313725

In [0]:
np.median(arr)

50.5

## Effect of scaling arrays on mean and median

In [0]:
arr = np.random.rand(100)

In [0]:
np.mean(arr)

0.4383130659902099

In [0]:
np.median(arr)

0.3970390836194846

In [0]:
arr1 = 2.5 * arr + 0.65

In [0]:
print(np.mean(2.5 * arr + 0.65), 
      2.5 * np.mean(arr) + 0.65)

1.7457826649755248 1.7457826649755246


In [0]:
print(np.median(2.5 * arr + 0.65), 
      2.5 * np.median(arr) + 0.65)

1.6425977090487114 1.6425977090487116


In [0]:
print(np.var(2.5 * arr + 0.65), 
      2.5*2.5*np.var(arr))

0.4164288169548459 0.4164288169548459


In [0]:
print(np.std(2.5 * arr + 0.65), 
      2.5 * np.std(arr))

0.6453129604733241 0.6453129604733241


In [0]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [0]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.29677089842238513 -0.29677089842238513
