In [14]:
import pandas as pd
import numpy as np
import ssl
import urllib.request
import seaborn as sns
import matplotlib.pyplot as plt

## Adding Dummy Features
Augemnts dataset with a column vector, each value in vector is 1. This is useful for adding a parameter for bias term in model.

In [15]:
x = np.array([
    [7, 1],
    [1, 8],
    [2, 0],
    [9, 6]
])

In [16]:
from sklearn.preprocessing import add_dummy_feature

x_new = add_dummy_feature(x)

print(x_new)

[[1. 7. 1.]
 [1. 1. 8.]
 [1. 2. 0.]
 [1. 9. 6.]]


## Custom Transformers
Enables conversion of an exsiting Python function into a transformer to assist in data clening or processing.
Useful when
1. The dataset consists of hetergenous types (eg raster images, text caption etc)
2. The dataset is stored in a pandas.Dataframes and different columns require different processing pipelines.
3. We need stateless transformations such as taking the log of frequencies, custom scaling etc


In [17]:
from sklearn.preprocessing import FunctionTransformer

In [19]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
context = ssl._create_unverified_context()
data = urllib.request.urlopen(url, context=context)
wine_data = pd.read_csv(data, sep=';')

In [20]:
wine_data.describe()

fixed acidity  volatile acidity  ...      alcohol      quality
count    1599.000000       1599.000000  ...  1599.000000  1599.000000
mean        8.319637          0.527821  ...    10.422983     5.636023
std         1.741096          0.179060  ...     1.065668     0.807569
min         4.600000          0.120000  ...     8.400000     3.000000
25%         7.100000          0.390000  ...     9.500000     5.000000
50%         7.900000          0.520000  ...    10.200000     6.000000
75%         9.200000          0.640000  ...    11.100000     6.000000
max        15.900000          1.580000  ...    14.900000     8.000000

[8 rows x 12 columns]

In [21]:
wine_data.describe().T # Transpose

count       mean  ...        75%        max
fixed acidity         1599.0   8.319637  ...   9.200000   15.90000
volatile acidity      1599.0   0.527821  ...   0.640000    1.58000
citric acid           1599.0   0.270976  ...   0.420000    1.00000
residual sugar        1599.0   2.538806  ...   2.600000   15.50000
chlorides             1599.0   0.087467  ...   0.090000    0.61100
free sulfur dioxide   1599.0  15.874922  ...  21.000000   72.00000
total sulfur dioxide  1599.0  46.467792  ...  62.000000  289.00000
density               1599.0   0.996747  ...   0.997835    1.00369
pH                    1599.0   3.311113  ...   3.400000    4.01000
sulphates             1599.0   0.658149  ...   0.730000    2.00000
alcohol               1599.0  10.422983  ...  11.100000   14.90000
quality               1599.0   5.636023  ...   6.000000    8.00000

[12 rows x 8 columns]

In [22]:
transformer = FunctionTransformer(np.log1p, validate=True)

wine_data_transformed = transformer.transform(np.array(wine_data))

pd.DataFrame(wine_data_transformed, columns=wine_data.columns).describe().T

count      mean       std  ...       50%       75%       max
fixed acidity         1599.0  2.215842  0.178100  ...  2.186051  2.322388  2.827314
volatile acidity      1599.0  0.417173  0.114926  ...  0.418710  0.494696  0.947789
citric acid           1599.0  0.228147  0.152423  ...  0.231112  0.350657  0.693147
residual sugar        1599.0  1.218131  0.269969  ...  1.163151  1.280934  2.803360
chlorides             1599.0  0.083038  0.038991  ...  0.076035  0.086178  0.476855
free sulfur dioxide   1599.0  2.639013  0.623790  ...  2.708050  3.091042  4.290459
total sulfur dioxide  1599.0  3.634750  0.682575  ...  3.663562  4.143135  5.669881
density               1599.0  0.691519  0.000945  ...  0.691521  0.692064  0.694990
pH                    1599.0  1.460557  0.035760  ...  1.460938  1.481605  1.611436
sulphates             1599.0  0.501073  0.093731  ...  0.482426  0.548121  1.098612
alcohol               1599.0  2.431458  0.090434  ...  2.415914  2.493205  2.766319
quality               1599.0  1.885054  0.122749  ...  1.945910  1.945910  2.197225

[12 rows x 8 columns]

## Polynomial Features

Generate Polynomial Features

In [25]:
from sklearn.preprocessing import PolynomialFeatures

wine_data_copy = wine_data.copy()

print("Number of features before transformation: ", wine_data.shape)


poly = PolynomialFeatures(degree=2)
poly_wine_data = poly.fit_transform(wine_data)

print("Number of features before transformation: ", poly_wine_data.shape)

Number of features before transformation:  (1599, 12)
Number of features before transformation:  (1599, 91)


In [26]:
poly.get_feature_names_out()

array(['1', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality', 'fixed acidity^2', 'fixed acidity volatile acidity',
       'fixed acidity citric acid', 'fixed acidity residual sugar',
       'fixed acidity chlorides', 'fixed acidity free sulfur dioxide',
       'fixed acidity total sulfur dioxide', 'fixed acidity density',
       'fixed acidity pH', 'fixed acidity sulphates',
       'fixed acidity alcohol', 'fixed acidity quality',
       'volatile acidity^2', 'volatile acidity citric acid',
       'volatile acidity residual sugar', 'volatile acidity chlorides',
       'volatile acidity free sulfur dioxide',
       'volatile acidity total sulfur dioxide',
       'volatile acidity density', 'volatile acidity pH',
       'volatile acidity sulphates', 'volatile acidity alcohol',
       'volatile acidity quality', 'citric acid^2',
       'c

## Discretization

Discretization or Quantisation or Binning provides a way to partition continuous features into discrete values.

In [28]:
from sklearn.preprocessing import KBinsDiscretizer

wine_data_copy_2 = wine_data_copy.copy()

enc = KBinsDiscretizer(n_bins=10, encode="onehot")
X = np.array(wine_data['chlorides']).reshape(-1, 1)
X_binned = enc.fit_transform(X)

In [29]:
X_binned

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1599 stored elements and shape (1599, 10)>

In [30]:
X_binned.toarray()[:10]

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

## Handling Categorical Data